### ISSUE TITLE
USER STORY: Bulletin Board

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#1]
As a **Site User** I can **view a paginated list of post** so that I can **see what services/requests are being offered/solicited and get more information about the ones I'm interested in**.

## Acceptance Criteria
* Acceptance Criteria 1: Posts of both types (service/request) are visible on the bulletin board page. These posts should be the contents of the Post model.
* Acceptance Criteria 2: Have the following fields from the Post model visible on each post: post_type, title, username, blurb, featured_image, created_on, payment_type, and rate.
* Acceptance Criteria 3: If the the user has not uploaded their own image to the 'featured_image' field, have a default, placeholder image display with the post instead.
* Acceptance Criteria 4: Each post is a clickable link to get more information (where the link leads will be dealt with by the User Story: Post Details).
* Acceptance Criteria 5: Pagination occurs after 5 posts.

## Dependencies
* EPIC: Initial Setup

## Tasks
- [x] Create a view that will get the contents of the Post model, uses a HTML template name for the Bulletin Board, that you will create soon after this task, and paginates after 5 posts.
- [x] Create a base.html template.
- [x] Create a HTML page for the Bulletin Board, which extends base.html, displays each of the posts in Post Model, displays the fields mentions in the acceptance criteria, and makes each post a link with an empty href attribute (for now).
- [x] Connect up URLs in the urls.py file.
- [x] Create more than 5 posts using the Admin Site, and check that pagination occurs after 10 posts.
