### ISSUE TITLE
USER STORY: Create Post

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#10]
As a **Site User** I can **create a post** so that I can **add content to the website**.

## Acceptance Criteria
* Acceptance Criteria 1: Create post link appears on bulletin board page.
* Acceptance Criteria 2: Link leads to a page where User can input the relevant info. 
* Acceptance Criteria 3: On form submit, the data inputted gets added to the post model.
* Acceptance Criteria 4: After from submit, the User is redirected to a post success page, which let's them know their post was successfully created, and provides a link to view the post detail page.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board (so we can test the link from that page)
* USER STORY: Post Details

## Tasks
- [x] Install crispy forms package.
- [x] Make forms.py and, within it, the PostForm ModelForm class, using custom labels and widgets where needed.
- [x] Make the PostCreate class view, which will have both a get and post method.
- [x] Make a HTML template to house the form, including csrf token and crispy forms.
- [x] Make a HTML template to show to User after successful form submission, including a link to view Post Details page.
- [x] Add create post link to Bulletin Board page.
- [x] Connect up URLs using the urls.py file and HTML templating.
