### ISSUE TITLE
USER STORY: Post Details

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#11]
As a **Site User** I can **click on post on the Bulletin Board and be taken to a dedicated page for that post** so that I can **get more information about the post**.

## Acceptance Criteria
* Acceptance Criteria 1: Clicking on a post on the Bulletin Board take you to a new page with the following fields of Post model displayed: post_type, title, username, updated_on, created_on, description, featured_image, blurb, payment_type and rate.
* Acceptance Criteria 2: The URL of the new page is unique, and includes the slug field, username and the post's id.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board

## Tasks
- [x] Create a view with a get method that will be able to determine which post in the Post model the User has clicked on.
- [x] Create a HTML template for displaying post details, which extends base.html, and displays the fields mentioned above in the acceptance criteria. 
- [x] Link up the URLS in the urls.py file, add the new URL to the individual posts in Bulletin Board HTML template, making sure that the post's slug and id fields are being sent to the view.
