### ISSUE TITLE
USER STORY: View User's Posts (Profile Page)

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#12]
As a **Site User** I can **view a User's Profile Page (including mine own), which contains a list of all posts from that User** so that I can **either keep track of my own posts, or get more information about another Users services/requests**.

## Acceptance Criteria
* Acceptance Criteria 1: Usernames attached to posts on the Bulletin Board are links to the poster's Profile page.
* Acceptance Criteria 2: The Profile Page contains a list of all posts created by that User.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board
* USER STORY: Post Details

## Tasks
- [x] Create another superuser, and create a post using the new superuser as the username.
- [x] Create view to collect all the posts of a User.
- [x] Create a HTML template for the Profile Page that will display all the User's posts.
- [x] Connect up URLs using the urls.py file and HTML templating.
- [x] On Bulletin Board, click on the username on a post created by the new user, and check that the profile page you're taken to only displays the post you've created with that User.
