### ISSUE TITLE
USER STORY: Split Bulletin Board

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#14]
As a **Site User** I can **choose to view either services or requests on the Bulletin Board** so that I can **filter just the type of posts I'm searching**.

## Acceptance Criteria
* Acceptance Criteria 1: Bulletin Board URL takes you to a page where there's at least the following button links: 'Services' and 'Requests'.
* Acceptance Criteria 2: When 'Services' link is clicked, User is taken to a page displaying on the posts with 'post_type' Service.
* Acceptance Criteria 3: When 'Requests' link is clicked, User is taken to a page displaying on the posts with 'post_type' Request.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board

## Tasks
- [x] Create list views which filter services and requests respectively, as well another view which just renders the buttons links on a Bulletin Board landing page.
- [x] Create new HTML templates to break the Bulletin Board into 3 pages.
- [x] Connect up URLs in urls.py file and using templating in the HTML.
