### ISSUE TITLE
USER STORY: Edit Post

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#15]
As a **Site User** I can **edit my posts** so that I can **makes changes after the initial posting**.

## Acceptance Criteria
* Acceptance Criteria 1: There's an edit button under each post, which can be seen on the User's profile page.
* Acceptance Criteria 2: The User must be logged into the account that created the posts to be able to edit them.
* Acceptance Criteria 3: Edit button link leads to a page where User can alter the post info.
* Acceptance Criteria 4: On form submit, the data inputted gets added to the Post model.
* Acceptance Criteria 5: After from submit, the User is redirected to a post success page, which let's them know their post was successfully edited, and provides a link to view the post detail page.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board
* USER STORY: Post Details
* USER STORY: View User's Posts (Profile Page)
* USER STORY: Allauth/User Autorization Management

## Tasks
- [x] Make the PostEdit class view, which will have both a get and post method.
- [x] Make a HTML template to house the form, including csrf token and crispy forms.
- [x] Make a HTML template to show to User after successful form submission, including a link to view Post Details page.
- [x] Add the Edit button HTML to the profile page, as well an authorization check.
- [x] Connect up URLs using the urls.py file and HTML templating.
