### ISSUE TITLE
USER STORY: Delete Post

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#16]
As a **Site User** I can **delete my posts** so that I can **remove posts that I have no more need for**.

## Acceptance Criteria
* Acceptance Criteria 1: There's a delete button under each post, which can be seen on the User's profile page.
* Acceptance Criteria 2: The User must be logged into the account that created the posts to be able to delete them.
* Acceptance Criteria 3: On delete button click, the post gets deleted from the Post model.
* Acceptance Criteria 4: After delete button click, the User is redirected to a delete success page, which let's them know their post was successfully deleted, and provides a link to view their profile page.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board
* USER STORY: Post Details
* USER STORY: View User's Posts (Profile Page)
* USER STORY: Allauth/User Autorization Management

## Tasks
- [x] Make the PostDelete class view, which will have both a get method.
- [x] Make a HTML template to show to User after successful deletion, including a link to view User's profile page.
- [x] Add the Delete button HTML to the profile page, as well an authorization check.
- [x] Connect up URLs using the urls.py file and HTML templating.
