### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#17]
As a **Site User** I can **view a home page** so that I can **get a general understanding of the site's purpose**.

## Acceptance Criteria
* Acceptance Criteria 1: At website's root URL, there's a site logo and a brief description of the site's purpose.

## Dependencies
* Epic: Initial Setup

## Tasks
- [x] Create class based view to render the index.html.
- [x] Create index.html, which includes logo and a brief description of the site's purpose.
- [x] Connect up URLs using the urls.py file and HTML templating.
