### ISSUE TITLE
USER STORY: Post Model

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#2]
As a **Site Admin** I can **use a Django model to store User posts in the database** so that I can **simply and speed up my database entry, alteration, and maintenance.**.

## Acceptance Criteria
* Acceptance Criteria 1: The model includes, at least, the following fields: post_type, title, slug, username, updated_on, created_on, description, featured_image, blurb, payment_type and rate.
* Acceptance Criteria 2: Cloudinary is used to store the content of the 'featured_image' field.
* Acceptance Criteria 3: The 'username' field uses Django in-built User model as a foreign key.
* Acceptance Criteria 4: The 'updated_on' and 'created_on' fields are automatically populated with the current time.

## Dependencies
* USER STORY: Django Setup & Deployment

## Tasks
- [x] In models.py file, import models, User and CloudinaryField.
- [x] Create a Post class that inherits Django's models.Model. 
- [x] Add the required fields to the Post model, linking the 'username' filed to the User model through a foreign key, adding the Cloudinary field for 'featured_image', and setting the 'updated_on' and 'created_on' fields to 'models.DateTimeField(auto_now=True)'.
- [x] Configure any limited choice fields, eg 'post_type', in accordance with the Django documentation
- [x] Add a __str__(self) method to just return the 'title' field of the Post.
