### ISSUE TITLE
USER STORY: Allauth/User Autorization Management

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#20]
As a **Site Admin** I can **use the Allauth package** so that I can **simplify User authorization management**.

## Acceptance Criteria
* Acceptance Criteria 1: Alluth is installed, so that it can be used to handle, as least: User logins, logouts and signups.

## Dependencies
* EPIC: Initial Setup

## Tasks
- [x] Install the django allauth package and add to requirements.txt.
- [x] Add allauth URL to urls.py.
- [x] In settings.py, update installed apps, add site_id and add redirect locations for login and logout.
- [x] Migrate the changes.
