### ISSUE TITLE
USER STORY: Admin Site

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#3]
As a **Site Admin** I can **access the Django admin panel** so that I can **create posts and test the Post model's fields functionality.**.

## Acceptance Criteria
* Acceptance Criteria 1: Using a superuser login, I can access the Django admin panel.
* Acceptance Criteria 2: The Post model is visible in the admin panel.
* Acceptance Criteria 3: Summernote WYSIWYG editor appears for the 'description' field when creating a new post.
* Acceptance Criteria 4: The 'slug' field gets prepopulated as you add content to the 'title' field.
* Acceptance Criteria 5: I can successfully add a post to the Post model. At least one post should be created.

## Dependencies
* USER STORY: Django Setup & Deployment
* USER STORY: Post Model

## Tasks
- [x] Create Django superuser.
- [x] Register the Post model in admin.py file.
- [x] Install summernote package, and use it for the 'description' field of the Post model.
- [x] Prepopulate 'slug' field with slugified text from the 'title' field.
- [x] Create a post so the Post model has some contents.
