### ISSUE TITLE
USER STORY: Django Setup & Deployment

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#5]
As a **Site Admin** I can **use a deployed Django framework** so that I can **simplify and speed up the site creation process**.

## Acceptance Criteria
* Acceptance Criteria 1: There's GitHub repository created that's based on the Code Institute template.
(https://github.com/Code-Institute-Org/gitpod-full-template)
* Acceptance Criteria 2: Within the repository, there's a Django project and app created.
* Acceptance Criteria 3: There's an external database.
* Acceptance Criteria 4: There's a Heroku app, connected to this external database, as well as our repository, with the secret key being hidden from GitHub pushes. 
* Acceptance Criteria 5: Cloudinary is set up to host the site's static and media files.
* Acceptance Criteria 6: The site is deployed with Heroku.

## Dependencies
* None :)

## Tasks
- [x] Make new repository based on the Code Institute template.
- [x] Install Django, gunicorn, dj_database_url, psycopg2 and cloudinary storage.
- [x] Create requirements.txt file and add the installed a packages to it.
- [x] Create Django project, app and migrate the changes.
- [x] Create external ElephantSQL database.
- [x] Create Heroku app.
- [x] Connect up ElephantSQL, Heroku app and your repository, making sure to put database url and secret key into a Git ignored env.py file. Then, migrate changes.
- [x] Create Cloudinary account, linking it to your repository and Heroku app.
- [x] Create Profile and top level folders 'media', 'static', and 'templates'.
- [x] Git commit, push to GitHub, and use GitHub method to deploy with Heroku.
