### ISSUE TITLE
USER STORY: View Post Reviews

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#7]
As a **Site User** I can **view review scores for posts** so that I can **have useful information when deciding whether or not I should engage with the post and trust the poster**.

## Acceptance Criteria
* Acceptance Criteria 1: Average post review scores visible on the bulletin board posts.
* Acceptance Criteria 2: Average post review scores visible on the user profile page, .
* Acceptance Criteria 3: Individual post review scores visible on the service details page.

## Dependencies
* EPIC: Initial Setup
* USER STORY: Bulletin Board (so we can test the link from that page)
* USER STORY: Post Details
* USER STORY: View User's Posts (Profile Page)

## Tasks
- [x] Create a method on the post model for calculating the mean average of the review ratings.
- [x] Add average post review scores to the HTML templates for the bulletin board and the profile page (accessing through the post model instance).
- [x] Add reviews to the post detail view.
- [x] Add reviews to the post detail HTML template.
