### ISSUE TITLE
USER STORY: PostReview Model

### ISSUE THREAD

**Issue by adammkeane** [adammkeane/work-app-pp4#8]
As a **Site Admin** I can **use a Django model to store User reviews in the database** so that I can **simplify the management of that data**.

## Acceptance Criteria
* Acceptance Criteria 1: The model includes, at least, the following fields: post, title, username, updated_on, created_on, rating and, description.
* Acceptance Criteria 2: The 'post' field uses our Post model as a foreign key
* Acceptance Criteria 3: The 'username' field uses Django in-built User model as a foreign key.
* Acceptance Criteria 4: The 'updated_on' and 'created_on' fields are automatically populated with the current time.

## Dependencies
* Epic: Initial Setup

## Tasks
- [x] In models.py file, Create a PostReview class that inherits Django's models.Model. 
- [x] Add the required fields to the PostReview model, linking the 'username' filed to the User model through a foreign key, linking the 'post' field to the Post Model through a foreign key, and setting the 'updated_on' and 'created_on' fields to 'models.DateTimeField(auto_now=True)'.
- [x] Configure any limited choice fields, eg 'rating', in accordance with the Django documentation
- [x] Add a __str__(self) method to just return the 'title' field of the PostReview.
